# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IA_Yf2TipQ4YpXIOlY8c4Nvd6fvNs3cZ
"""

pip install gradio

def generate_recipe_prompt():
    ingredients_input = input("Enter the ingredients separated by comma: ")
    ingredients = ingredients_input.split(",")

    # Create a placeholder recipe prompt
    recipe_prompt = "Write a recipe based on the ingredients provided here:\n"

    # Concatenate the ingredients into the recipe prompt
    recipe_prompt += "Ingredients:\n"
    for ingredient in ingredients:
        recipe_prompt += f"- {ingredient.strip()}\n"

    # You can add more customization here, such as searching for recipes online based on the ingredients

    return recipe_prompt

# Generate recipe prompt
print(generate_recipe_prompt())